name: Build IMU Mocap Viewer

on: [push, pull_request]

jobs:
  buildDesktopPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: "IMU Mocap Viewer/Library"
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "./IMU Mocap Viewer"
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
          buildsPath: "build/"
          buildName: 'IMU Mocap Viewer'

      - if: ${{ matrix.targetPlatform }} == 'StandaloneWindows64'
        name: Create installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" WindowsInstaller.iss

      - if: ${{ matrix.targetPlatform }} == 'StandaloneWindows64'
        uses: actions/upload-artifact@v4
        with:
          name: "IMU Mocap Viewer - ${{ matrix.targetPlatform }}"
          path: "Output/*.exe"

      - if: ${{ matrix.targetPlatform }} != 'StandaloneWindows64'
        uses: actions/upload-artifact@v4
        with:
          name: "IMU Mocap Viewer - ${{ matrix.targetPlatform }}"
          path: "build/${{ matrix.targetPlatform }}"