name: CI

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v4

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }}

  examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install matplotlib
          python -m pip install numpy
          python -m pip install scipy
          python -m pip install ximu3csv

      - name: Install Python package
        run: python -m pip install .

      - name: Run examples
        working-directory: Examples
        run: |
          python animate_body.py dont_block
          python animate_body_with_hands.py dont_block
          python animate_body_with_wheelchair.py dont_block
          python animate_body_with_wheelchair_and_hands.py dont_block
          python animate_left_hand.py dont_block
          python animate_right_hand.py dont_block
          python logged_lower_body.py dont_block

  imu-mocap-viewer:
    runs-on: ${{ matrix.target[0] }}
    strategy:
      fail-fast: false
      matrix:
        target: # [ os, name, platform  ]
          - [ macos-latest, macOS, StandaloneOSX ]
          - [ windows-latest, Windows, StandaloneWindows64 ]
          - [ ubuntu-latest, ubuntu, StandaloneLinux64 ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: "IMU Mocap Viewer/Library"
          key: Library-${{ matrix.target[0] }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "./IMU Mocap Viewer"
          targetPlatform: ${{ matrix.target[2] }}
          allowDirtyBuild: true
          buildsPath: "build/"
          buildName: 'IMU Mocap Viewer'
          versioning: Custom
          version: '0.0.0'

      - uses: actions/upload-artifact@v4
        with:
          name: IMU-Mocap-Viewer-${{ matrix.target[1] }}
          path: |
            build/${{ matrix.target[2] }}
            !build/${{ matrix.target[2] }}/*DoNotShip

  macos-dmg:
    runs-on: macos-latest
    needs: imu-mocap-viewer

    steps:
      - uses: actions/checkout@v4

      - name: Download from artifacts
        uses: actions/download-artifact@v4
        with:
          name: IMU-Mocap-Viewer-macOS

      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
          --volname "IMU-Mocap-Viewer" \
          --background "installer_background.png" \
          --window-pos 200 120 \
          --window-size 600 320 \
          --icon-size 100 \
          --icon "IMU Mocap Viewer.app" 140 130 \
          --hide-extension "IMU Mocap Viewer.app" \
          --app-drop-link 450 125 \
          "IMU-Mocap-Viewer.dmg" \
          "IMU Mocap Viewer.app"

      - uses: actions/upload-artifact@v4
        with:
          name: IMU-Mocap-Viewer.dmg
          path: IMU-Mocap-Viewer.dmg

  windows-installer:
    runs-on: windows-latest
    needs: imu-mocap-viewer

    steps:
      - uses: actions/checkout@v4

      - name: Download from artifacts
        uses: actions/download-artifact@v4
        with:
          name: IMU-Mocap-Viewer-Windows
          path: files

      - name: Create installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" WindowsInstaller.iss

      - uses: actions/upload-artifact@v4
        with:
          name: IMU-Mocap-Viewer-Setup.exe
          path: Output/IMU-Mocap-Viewer-Setup.exe
